# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WesideCli < Formula
  desc "CLI for the weside.ai AI Companion Platform"
  homepage "https://weside.ai"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.2.0/weside-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "5f33fb49938d2aeedbd043f035f66027f78345b95c31f95bd44e6f64dba2987a"

      define_method(:install) do
        bin.install "weside"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.2.0/weside-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "cc98dd4dee6a9c01eb24a7c514938403ac8c68e788d4c1717b3aac11af7b39fd"

      define_method(:install) do
        bin.install "weside"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.2.0/weside-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "5ea4d6a7450e25b73c319c9b92ea34b804b2873d6d1c4b2d99af1e8957f2568c"
      define_method(:install) do
        bin.install "weside"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.2.0/weside-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "26b34eda29cf016e598abe8c1f153198805ae81a29e1c5c0c402a68f692667e0"
      define_method(:install) do
        bin.install "weside"
      end
    end
  end

  test do
    system "#{bin}/weside", "version"
  end
end
