# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WesideCli < Formula
  desc "CLI for the weside.ai AI Companion Platform"
  homepage "https://weside.ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.1.0/weside-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "a4cbc187a33412dabc79b55a572f4ba2b9aeecbfbb78499412d318e3639853af"

      define_method(:install) do
        bin.install "weside"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.1.0/weside-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "5fb908ce58351897f7128ecbc2270ae1c243569e22b9f3676d8fc7b021be4456"

      define_method(:install) do
        bin.install "weside"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.1.0/weside-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "9aa9611283015bdecf1953770ef19967995e60f72046a7474b87626505d99236"
      define_method(:install) do
        bin.install "weside"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weside-ai/weside-cli/releases/download/v0.1.0/weside-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "a9b53c59c9a3eeb86137a5772c39ed6a3ae6c945d4623c33500c27eccdbe251b"
      define_method(:install) do
        bin.install "weside"
      end
    end
  end

  test do
    system "#{bin}/weside", "version"
  end
end
