# This file was generated by GoReleaser. DO NOT EDIT.
cask "weside-cli" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "fdeba3a63e081786e4befc5e790589118ac918e20f0ac77d7f0b9083526ee900"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
    on_arm do
      sha256 "e6f46e567b31b6c4535ce190d463109c25b74beb360bd31113b838641bcd70ad"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa47a03c7e3332f6150eeeb93074e23a962c15a7bf9b318321bc861ca935c6b9"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
    on_arm do
      sha256 "b57bf3b4f9181284c79c8a36974e87555984143e7ae8de561d68310d868b3b16"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
  end

  name "weside-cli"
  desc "CLI for the weside.ai AI Companion Platform"
  homepage "https://weside.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weside"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/weside"]
    end
  end

  # No zap stanza required

end
