# This file was generated by GoReleaser. DO NOT EDIT.
cask "weside-cli" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "6ebdfd4acccb6e0aee321584b05f3abb3a463350b58c0bbac9ff67549f0ed79d"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
    on_arm do
      sha256 "bc6403380f46ade5360c0cbf7a698dfce6561ebd70cb624bbf684b1321d56a80"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d6b8792647254bf34b43d1cf00b73df7255dd2882b8e0649e6286a15c6dbea2"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
    on_arm do
      sha256 "f9a06dc38f6dcaf70f7a3056037fecff6ab68c3361eed7171c126c5e84135199"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
  end

  name "weside-cli"
  desc "CLI for the weside.ai AI Companion Platform"
  homepage "https://weside.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weside"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/weside"]
    end
  end

  # No zap stanza required

end
