# This file was generated by GoReleaser. DO NOT EDIT.
cask "weside-cli" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "586c7816a012ce124052ba04820bac730a27a78501c9028243a1382156b75b03"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
    on_arm do
      sha256 "ac688b520925f5cbdb9ee2705f725190068552c5c6f311df0a4e618aebe2a9e5"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6b998e286e367812d9834befcf7e71dbbdbdcdaa9bc5d476459248706abf010"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
    on_arm do
      sha256 "ed9beb33154e1748368f2d6ae5aedf25d832ef8ff038af44d426af988b1c842a"
      url "https://github.com/weside-ai/weside-cli/releases/download/v#{version}/weside-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/weside-ai/weside-cli/"
    end
  end

  name "weside-cli"
  desc "CLI for the weside.ai AI Companion Platform"
  homepage "https://weside.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "weside"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/weside"]
    end
  end

  # No zap stanza required

end
